SET SERVEROUTPUT ON SIZE 1000000

-- WARNING: Destructive script. This will permanently DROP the listed tables (no backups).
-- Run only if you are certain you want to remove existing data.

DECLARE
  cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'AUDIT_LOGS';
  IF cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped AUDIT_LOGS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('AUDIT_LOGS not found, skipping drop');
  END IF;

  SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'FILE_METADATA';
  IF cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE FILE_METADATA CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped FILE_METADATA');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FILE_METADATA not found, skipping drop');
  END IF;

  SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'FILE_PASSWORDS';
  IF cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE FILE_PASSWORDS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped FILE_PASSWORDS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FILE_PASSWORDS not found, skipping drop');
  END IF;

  SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'SECURITY_QUESTIONS';
  IF cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE SECURITY_QUESTIONS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped SECURITY_QUESTIONS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SECURITY_QUESTIONS not found, skipping drop');
  END IF;

  SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = 'USERS';
  IF cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped USERS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('USERS not found, skipping drop');
  END IF;

  COMMIT;
END;
/

-- Create minimal tables required by the application
-- 1) USERS
CREATE TABLE USERS (
  USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(150 CHAR) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
  PASSWORD_SALT VARCHAR2(255 CHAR),
  EMAIL VARCHAR2(255 CHAR),
  ACCOUNT_STATUS VARCHAR2(50 CHAR) DEFAULT 'ACTIVE',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_LOGIN TIMESTAMP
);

-- 2) SECURITY_QUESTIONS
CREATE TABLE SECURITY_QUESTIONS (
  QUESTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  QUESTION_TEXT VARCHAR2(1024 CHAR),
  ANSWER_HASH VARCHAR2(255 CHAR),
  ANSWER_SALT VARCHAR2(255 CHAR),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_SECURITY_QUESTIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 3) FILE_PASSWORDS
CREATE TABLE FILE_PASSWORDS (
  FP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  ENCRYPTED_FILE_PASSWORD VARCHAR2(2048 CHAR),
  FP_SALT VARCHAR2(512 CHAR),
  ENCRYPTION_ALGORITHM VARCHAR2(100 CHAR),
  ITERATIONS NUMBER DEFAULT 100000,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_FILE_PASSWORDS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4) FILE_METADATA
CREATE TABLE FILE_METADATA (
  FILE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  OWNER_ID NUMBER NOT NULL,
  ORIGINAL_FILENAME VARCHAR2(1024 CHAR),
  STORED_FILENAME VARCHAR2(1024 CHAR),
  FILE_SIZE NUMBER,
  IV VARCHAR2(512 CHAR),
  SALT VARCHAR2(512 CHAR),
  ENCRYPTION_ALGORITHM VARCHAR2(100 CHAR),
  COMPRESSION_FLAG CHAR(1) DEFAULT 'N',
  FILE_PATH VARCHAR2(2000 CHAR),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_FILE_METADATA_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 5) AUDIT_LOGS
CREATE TABLE AUDIT_LOGS (
  LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID NUMBER,
  FILE_ID NUMBER,
  OPERATION_TYPE VARCHAR2(50 CHAR),
  OPERATION_STATUS VARCHAR2(50 CHAR),
  FILE_SIZE NUMBER,
  DURATION_MS NUMBER,
  ERROR_MESSAGE VARCHAR2(2000 CHAR),
  TIMESTAMP_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_AUDIT_LOGS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_AUDIT_LOGS_FILE FOREIGN KEY (FILE_ID) REFERENCES FILE_METADATA(FILE_ID) ON DELETE SET NULL
);

-- Helpful indexes
CREATE INDEX IDX_FILE_METADATA_OWNER ON FILE_METADATA (OWNER_ID);
CREATE INDEX IDX_SECURITY_QUESTIONS_USER ON SECURITY_QUESTIONS (USER_ID);
CREATE INDEX IDX_FILE_PASSWORDS_USER ON FILE_PASSWORDS (USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_USER ON AUDIT_LOGS (USER_ID);

COMMIT;

PROMPT "Destructive refresh completed. All old tables dropped (if present) and new minimal tables created."
